### ISSUE TITLE
“break down” 似乎不是“分解”

### ISSUE THREAD

**Issue by gezinfly** [Obsoletes/Rimworld#2]
https://github.com/Obsoletes/Rimworld/blob/cbc013e5e4caea5f3f79b22c917e83ea81af1f29/Dev%20In%20Your%20Language_zh/Languages/ChineseSimplified/Keyed/Actions.xml#L295-L296
在这一行中， 有“损坏，故障”的意思，实际操作中，确实会导致生产设施进入需要零部件维修的状态，故怀疑翻译需要修改
在游戏中，官方简中是“故障”，在用“T：分解”点击在制冷机上后，左键制冷机的详情条目中多了一个“故障”条目，并在外观上显示红色的多芒星

**Comment by Obsoletes** [comment]
好的，谢谢

**Comment by gezinfly** [comment]
感谢
